package com.mb.web.domain;

public class Mytest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myTest.id
     *
     * @mbggenerated Mon Jul 25 16:41:37 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myTest.user_id
     *
     * @mbggenerated Mon Jul 25 16:41:37 CST 2016
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myTest.user_name
     *
     * @mbggenerated Mon Jul 25 16:41:37 CST 2016
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myTest.id
     *
     * @return the value of myTest.id
     *
     * @mbggenerated Mon Jul 25 16:41:37 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myTest.id
     *
     * @param id the value for myTest.id
     *
     * @mbggenerated Mon Jul 25 16:41:37 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myTest.user_id
     *
     * @return the value of myTest.user_id
     *
     * @mbggenerated Mon Jul 25 16:41:37 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myTest.user_id
     *
     * @param userId the value for myTest.user_id
     *
     * @mbggenerated Mon Jul 25 16:41:37 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myTest.user_name
     *
     * @return the value of myTest.user_name
     *
     * @mbggenerated Mon Jul 25 16:41:37 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myTest.user_name
     *
     * @param userName the value for myTest.user_name
     *
     * @mbggenerated Mon Jul 25 16:41:37 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}